apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sdashboard
---
# 需提供集群管理员权限来获得所有集群的信息
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sdashboard-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: k8sdashboard
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdashboard
  labels:
    app: k8sdashboard
spec:
  selector:
    matchLabels:
      app: k8sdashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: k8sdashboard
    spec:
      serviceAccountName: k8sdashboard
      containers:
      - name: k8sdashboard
        image: harbor.beautytiger.com/docker.io/k8sdashboard:0.1.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: k8sdashboard
  labels:
    app: k8sdashboard
spec:
  selector:
    app: k8sdashboard
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort